<html>
<head>
    <title>Mjolnir | Transcend</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            text-align: center;
            background-color: #0b0b0c;
            background-image: url("C:\Users\Ajay\Pictures\Screenshots\Screenshot 2023-07-07 162316.png");
            background-repeat: no-repeat;
            background-size: cover;
        }
		#video-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            z-index: -1;
        }

        #video {
            width: 100%;
            height: auto;
        }
        header {
            padding: 20px;
            margin-bottom: 20px;
            width: 100%;
            box-sizing: border-box;
            background-color: rgba(0, 0, 0, 0.5);
        }

        h1 {
            margin: 0;
			color: #fff;
        }

        p {
            margin: 10px 0;
			color: #fff;
        }

        section {
            padding: 20px;
            margin-bottom: 20px;
            width: 100%;
            box-sizing: border-box;
			color: #fff;
			background-color: rgba(0, 0, 0, 0.5);
        }

        #signup button {
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            border: none;
            cursor: pointer;
            margin-right: 10px;
        }

        #latest-newsletters {
            margin-top: 20px;
			color: #fff;
        }

        button {
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            border: none;
            cursor: pointer;
            margin-top: 10px;
        }
    </style>
    <script>
        function showAlert() {
            alert("This is an alert box!");
        }

        function showConfirmation() {
            var result = confirm("Are you sure you want to subscribe?");
            if (result) {
                alert("You have subscribed successfully!");
            } else {
                alert("Subscription canceled.");
            }
        }

        function showPrompt() {
            var name = prompt("Please enter your name:");
            if (name) {
                alert("Hello, " + name + "! Thanks for subscribing!");
            } else {
                alert("Subscription canceled.");
            }
        }
    </script>
</head>
<body> 
  <div id="video-container">
        <video id="video" autoplay loop muted>
            <source src="C:\Users\Ajay\Downloads\God of War III Launch Trailer.mp4" type="video/mp4">
        </video>
  </div>
  
  <header>
    <h1>Welcome to Our Newsletter</h1>
    <p>Stay up-to-date with the latest news and updates.</p>
  </header>

  <section id="signup">
    <h2>Sign up for our newsletter</h2>
    <button onclick="showConfirmation()">Subscribe</button>
  </section>

  <section id="latest-newsletters">
    <h2>Latest Newsletters</h2>
    <!-- Add your latest newsletters content here -->
  </section>

  <button onclick="showAlert()">Show Alert</button>
  <button onclick="showPrompt()">Show Prompt</button>
</body>
</html>
